# Generated by Django 3.1.6 on 2021-02-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='age',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
